name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy_canary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get -y install docker
          docker --version  # Vérifiez si Docker est installé correctement

      - name: Build Docker image
        run: |
                  docker build -t hickoom/voting-app:canary voting-app-helm/ 
                  docker push hickoom/voting-app:canary

      - name: Deploy Canary
        run: |
          helm upgrade --install voting-app-canary ./voting-app-chart --set image.repository=hickoom/votingapp --set image.tag=canary

          # Check if deployment succeeded
          STATUS=$(helm status voting-app-canary --output json | jq -r '.info.status')
          if [ "$STATUS" != "deployed" ]; then
            echo "Canary deployment failed. Rolling back..."
            helm rollback voting-app-canary 1
            exit 1
          fi

      - name: Test Canary
        run: |
          # Add test steps for the canary deployment

      - name: Promote Canary
        run: |
          helm upgrade --install voting-app ./voting-app-chart --set image.repository=hickoom/voting-app --set image.tag=v1
          helm delete voting-app-canary --purge
